version: '3.8'

services:
  db: 
      image: mysql:5.7
      container_name: db
      restart: always
      environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: wp_db
          MYSQL_USER: user
          MYSQL_PASSWORD: password
      ports:
          - "3306:3306"
      volumes:
          - ./db:/var/lib/mysql
      networks:
          - app-network

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      restart: always
      environment:
          PMA_HOST: db
          MYSQL_ROOT_PASSWORD: root
      ports:
          - "8080:80"
      networks:
          - app-network

  wordpress:
      image: wordpress:latest
      container_name: wordpress
      restart: always
      environment:
          WORDPRESS_DB_HOST: db:3306
          WORDPRESS_DB_USER: user
          WORDPRESS_DB_PASSWORD: password
          WORDPRESS_DB_NAME: wp_db
      ports:
          - "8000:80"
      volumes:
          - ./wordpress:/var/www/html
          - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      networks:
          - app-network


networks:
  app-network:
    driver: bridge